runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
syntax on
filetype plugin indent on
set tabstop=4
set expandtab
set softtabstop=4
set shiftwidth=4
filetype indent on
set background=dark

highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/

fun! StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    let _s=@/
    let @/=_s
    %s/\s\+$//e
    call cursor(l, c)
endfun

" Append modeline after last line in buffer.
" Use substitute() instead of printf() to handle '%%s' modeline in LaTeX
" files.
function! AppendModeline()
  let l:modeline = printf(" vim: set ts=%d sw=%d tw=%d %set :",
        \ &tabstop, &shiftwidth, &textwidth, &expandtab ? '' : 'no')
  let l:modeline = substitute(&commentstring, "%s", l:modeline, "")
  call append(line("$"), l:modeline)
endfunction
nnoremap <silent> <Leader>ml :call AppendModeline()<CR>

autocmd FileType c,cpp,java,php,ruby,python,perl,bash autocmd BufWritePre <buffer> :call StripTrailingWhitespaces()
autocmd FileType python set commentstring=#\%s
